/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param message 
 */


data class Ping200Response (

    @Json(name = "message")
    val message: kotlin.Any?

)

